-- ensure that the table with this name is removed before creating a new one.
DROP TABLE IF EXISTS project;

-- Create tg_user table
CREATE TABLE project
(
    id                    int primary key generated by default as identity,
    project_name          varchar,
    completion_date       timestamp,
    start_time_of_project timestamp,
    priority              int,
    status                varchar
);

DROP TABLE IF EXISTS task;
CREATE TABLE task
(
    id               int primary key generated by default as identity,
    task_name        varchar,
    task_description varchar,
    priority         int,
    task_status      varchar,
    project_id       int not null references project(id)
);